spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/threadly-user-auth-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#application:
#  security:
#    jwt:
#      secret-key: bZ1C/BhnIVRROhmEch4+xyoc1wc/aI9z1J1+gxRp5qACifGl3iVz3DczLoCZz382pFsjzlXwnLvMzKaf8sPjyA==
#      expiration: 86400000
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://threadly-service-discovery:8761/eureka/