spring:
  application:
    name:
      userAuthenticationService

  datasource:
    url: jdbc:postgresql://localhost:5432/threadly-user-auth-db
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port:
    8083

#  profiles:
#    active:
#      local







